//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY_STAFF()
        {
            this.ORDER_MASTER = new HashSet<ORDER_MASTER>();
        }
    
        public int DELIVERY_PERSON_ID { get; set; }
        public string DELIVERY_PERSON { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_MASTER> ORDER_MASTER { get; set; }
    }
}
