//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAILS
    {
        public int ORDER_DETAIL_ID { get; set; }
        public int ORDER_ID { get; set; }
        public int SUBMENU_ID { get; set; }
        public string TOPPING_IDS { get; set; }
        public Nullable<int> SUBMENU_VARIANT_ID { get; set; }
        public Nullable<decimal> TOTAL_TOPPING_AMOUNT { get; set; }
        public Nullable<decimal> ITEM_PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
    
        public virtual ORDER_MASTER ORDER_MASTER { get; set; }
        public virtual SUBMENU_MASTER SUBMENU_MASTER { get; set; }
        public virtual SUBMENU_VARIANT SUBMENU_VARIANT { get; set; }
    }
}
