//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public string CustomerID { get; set; }
        public int AddressID { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<decimal> DiscountOff { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int StatusID { get; set; }
        public int StoreID { get; set; }
        public int PaymentID { get; set; }
        public string Remark { get; set; }
        public string PromoCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string LastModifyBy { get; set; }
        public int PersonID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual DeliveryStaff DeliveryStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Store Store { get; set; }
    }
}
