//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMENU_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBMENU_MASTER()
        {
            this.ORDER_DETAILS = new HashSet<ORDER_DETAILS>();
            this.SUBMENU_VARIANT = new HashSet<SUBMENU_VARIANT>();
        }
    
        public int SUBMENU_ID { get; set; }
        public string SUBITEM_NAME { get; set; }
        public int MENU_ID { get; set; }
        public string SUBITEM_DESCRIPTION { get; set; }
        public string IMAGE_PATH { get; set; }
        public Nullable<bool> ISVARIANT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED_DATE { get; set; }
        public string LASTMODIFIED_BY { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    
        public virtual MENU_MASTER MENU_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAILS> ORDER_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBMENU_VARIANT> SUBMENU_VARIANT { get; set; }
    }
}
