//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOPPING
    {
        public int TOPPING_ID { get; set; }
        public int MENU_ID { get; set; }
        public string TOPPING_NAME { get; set; }
        public string VARIANT_DESCRIPTION { get; set; }
        public string IMAGE_PATH { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED_DATE { get; set; }
        public string LASTMODIFIED_BY { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    
        public virtual MENU_MASTER MENU_MASTER { get; set; }
    }
}
