//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TUGEntities : DbContext
    {
        public TUGEntities()
            : base("name=TUGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMER_ADDRESS> CUSTOMER_ADDRESS { get; set; }
        public virtual DbSet<DELIVERY_STAFF> DELIVERY_STAFF { get; set; }
        public virtual DbSet<MENU_MASTER> MENU_MASTER { get; set; }
        public virtual DbSet<ORDER_DETAILS> ORDER_DETAILS { get; set; }
        public virtual DbSet<ORDER_MASTER> ORDER_MASTER { get; set; }
        public virtual DbSet<ORDER_STATUS> ORDER_STATUS { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<STORE> STOREs { get; set; }
        public virtual DbSet<SUBMENU_MASTER> SUBMENU_MASTER { get; set; }
        public virtual DbSet<SUBMENU_VARIANT> SUBMENU_VARIANT { get; set; }
        public virtual DbSet<TOPPING> TOPPINGs { get; set; }
    }
}
